Config = {}

Config.Crafting = {
    {
        itemName = "lockpick",
        isGun = false,
        level = 0,
        levelUp = 1,
        Timer = 3000,
        price = 150,
        NeedItems = {
            ['refined_steel'] = 1,
        },
    },
    {
        itemName = "repairkit",
        isGun = false,
        level = 30,
        levelUp = 2,
        Timer = 6000,
        price = 1000,
        NeedItems = {
            ['refined_scrap'] = 1,
            -- ["refined_steel"] = 1,
        },
    },
    {
        itemName = "armor",
        isGun = false,
        level = 40,
        levelUp = 3,
        Timer = 10000,
        price = 3500,
        NeedItems = {
            ['refined_scrap'] = 1,
            ["refined_steel"] = 1,
            ["refined_rubber"] = 1,
        },
    },
}

Config.Melting = {
    {
        itemName = "smallgoldbar",
        isGun = false,
        level = 0,
        -- levelUp = 0,
        Timer = 3000,
        price = 100,
        NeedItems = {
            ['goldash'] = 20,
        },
    },
    {
        itemName = "refined_steel",
        isGun = false,
        level = 0,
        -- levelUp = 0,
        Timer = 3000,
        price = 50,
        NeedItems = {
            ['iron'] = 150,
            ['steel'] = 150,
        },
    },
    {
        itemName = "refined_scrap",
        isGun = false,
        level = 0,
        -- levelUp = 0,
        Timer = 3000,
        price = 50,
        NeedItems = {
            ['metalscrap'] = 150,
        },
    },
    {
        itemName = "refined_rubber",
        isGun = false,
        level = 0,
        -- levelUp = 0,
        Timer = 3000,
        price = 50,
        NeedItems = {
            ['rubber'] = 150,
            ['plastic'] = 150,
        },
    },
    {
        itemName = "refined_plastic",
        isGun = false,
        level = 0,
        -- levelUp = 0,
        Timer = 3000,
        price = 50,
        NeedItems = {
            ['rubber'] = 150,
            ['plastic'] = 150,
        },
    },
    {
        itemName = "refined_glass",
        isGun = false,
        level = 0,
        -- levelUp = 0,
        Timer = 3000,
        price = 50,
        NeedItems = {
            ['glass'] = 150,
        },
    },
    {
        itemName = "refined_copper",
        isGun = false,
        level = 0,
        -- levelUp = 0,
        Timer = 3000,
        price = 50,
        NeedItems = {
            ['copper'] = 150,
        },
    },
    {
        itemName = "refined_aluminium",
        isGun = false,
        level = 0,
        -- levelUp = 0,
        Timer = 3000,
        price = 50,
        NeedItems = {
            ['aluminum'] = 150,
        },
    },
}

Config.Crime = {
    {
        itemName = "lockpick",
        isGun = false,
        level = 0,
        levelUp = 1,
        Timer = 3000,
        price = 50,
        NeedItems = {
            ['refined_steel'] = 1,
        },
    },
    {
        itemName = "nylonrope",
        isGun = false,
        level = 0,
        levelUp = 1,
        Timer = 10000,
        price = 150,
        NeedItems = {
            ['refined_plastic'] = 1,
            ["refined_rubber"] = 1,
        },
    },
    {
        itemName = "laserdrill",
        isGun = false,
        level = 0,
        levelUp = 1,
        Timer = 10000,
        price = 500,
        NeedItems = {
            ['refined_steel'] = 1,
            ["refined_rubber"] = 1,
        },
    },
    {
        itemName = "repairkit",
        isGun = false,
        level = 0,
        levelUp = 1,
        Timer = 6000,
        price = 800,
        NeedItems = {
            ['refined_copper'] = 1,
        },
    },
    {
        itemName = "ziptie",
        isGun = false,
        level = 0,
        levelUp = 1,
        Timer = 3000,
        price = 100,
        NeedItems = {
            ['refined_plastic'] = 1,
            ["refined_rubber"] = 1,
        },
    },
    {
        itemName = "breaker",
        isGun = false,
        level = 0,
        levelUp = 2,
        Timer = 3000,
        price = 50,
        NeedItems = {
            ['refined_steel'] = 1,
            ['refined_aluminium'] = 1,
        },
    },
    {
        itemName = "hacking_device",
        isGun = false,
        level = 0,
        levelUp = 3,
        Timer = 3000,
        price = 200,
        NeedItems = {
            ['refined_plastic'] = 1,
            ['refined_aluminium'] = 1,
        },
    },
    {
        itemName = "armor",
        isGun = false,
        level = 0,
        levelUp = 1,
        Timer = 10000,
        price = 200,
        NeedItems = {
            ["refined_plastic"] = 2,
            ["refined_steel"] = 1,
        },
    },
    {
        itemName = "glasscutter",
        isGun = false,
        level = 0,
        levelUp = 1,
        Timer = 3000,
        price = 10000,
        NeedItems = {
            ['refined_scrap'] = 2,
            ['refined_copper'] = 2,
            ["refined_steel"] = 2,
            ["refined_rubber"] = 1,
            ["refined_glass"] = 4,
        },
        min = 1,
        max = 669,
    },
    {
        itemName = "gps_jammer",
        isGun = false,
        level = 0,
        levelUp = 1,
        Timer = 3000,
        price = 200,
        NeedItems = {
            ["metalscrap"] = 20,
            ["rubber"] = 20,
            ["plastic"] = 20,
            ["glass"] = 20,
        },
        min = 1,
        max = 669,
    },
    {
        itemName = "web_proxy",
        isGun = false,
        level = 0,
        levelUp = 1,
        Timer = 3000,
        price = 2000,
        NeedItems = {
            ['refined_scrap'] = 3,
            ["refined_rubber"] = 1,
            ["refined_glass"] = 3,
        },
        min = 1,
        max = 669,
    },
}